# Generated by Django 3.1 on 2020-09-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentsale',
            options={'verbose_name': 'apartament', 'verbose_name_plural': 'Apartamente'},
        ),
    ]
