# Generated by Django 3.1 on 2020-09-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200904_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentsale',
            options={'verbose_name': 'apartament', 'verbose_name_plural': 'apartamente'},
        ),
        migrations.AlterModelOptions(
            name='commercialspacesale',
            options={'verbose_name': 'spaţiu comercial', 'verbose_name_plural': 'Spaţii comerciale'},
        ),
        migrations.AlterModelOptions(
            name='housesale',
            options={'verbose_name': 'casă', 'verbose_name_plural': 'Case'},
        ),
        migrations.AlterModelOptions(
            name='industrialspacesale',
            options={'verbose_name': 'spaţiu industrial', 'verbose_name_plural': 'Spaţii industriale'},
        ),
        migrations.AlterModelOptions(
            name='landsale',
            options={'verbose_name': 'teren', 'verbose_name_plural': 'Terenuri'},
        ),
        migrations.AlterModelOptions(
            name='officesale',
            options={'verbose_name': 'birou', 'verbose_name_plural': 'Birouri'},
        ),
        migrations.AlterModelOptions(
            name='specialpropertysale',
            options={'verbose_name': 'proprietate specială', 'verbose_name_plural': 'Proprietăţi speciale'},
        ),
    ]
