# Generated by Django 3.1 on 2020-09-04 08:55

import ckeditor_uploader.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200904_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialspacesale',
            options={'verbose_name': 'spaţiu comercial', 'verbose_name_plural': 'spaţii comerciale'},
        ),
        migrations.AlterModelOptions(
            name='housesale',
            options={'verbose_name': 'casă', 'verbose_name_plural': 'case'},
        ),
        migrations.AlterModelOptions(
            name='industrialspacesale',
            options={'verbose_name': 'spaţiu industrial', 'verbose_name_plural': 'spaţii industriale'},
        ),
        migrations.AlterModelOptions(
            name='landsale',
            options={'verbose_name': 'teren', 'verbose_name_plural': 'terenuri'},
        ),
        migrations.AlterModelOptions(
            name='officesale',
            options={'verbose_name': 'birou', 'verbose_name_plural': 'birouri'},
        ),
        migrations.AlterModelOptions(
            name='specialpropertysale',
            options={'verbose_name': 'proprietate specială', 'verbose_name_plural': 'proprietăţi speciale'},
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
    ]
