# Generated by Django 3.1 on 2020-09-04 14:07

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200904_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentSaleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=main.utils.get_upload_path, verbose_name='imagine')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales.apartmentsale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
