# Generated by Django 3.1 on 2020-09-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20200904_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentSaleImage',
            new_name='ApartmentSaleImages',
        ),
    ]
