# Generated by Django 3.1 on 2020-09-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20200904_1159'),
        ('sales', '0012_auto_20200904_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
    ]
