# Generated by Django 3.1 on 2020-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20200908_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsale',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
    ]
