# Generated by Django 3.1 on 2020-09-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20200909_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsale',
            name='is_residential_complex',
            field=models.BooleanField(default=False, verbose_name='Ansamblu rezidenţial'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='residential_complex_link',
            field=models.URLField(blank=True, help_text='pagina detalii ansamblu rezidential promovat pe imobiliare.ro', null=True, verbose_name='Link'),
        ),
    ]
