# Generated by Django 3.1 on 2020-09-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20200909_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsale',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
    ]
