# Generated by Django 3.1 on 2020-09-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20200914_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialspacesale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='housesale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='industrialspacesale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='landsale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='officesale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='specialpropertysale',
            name='price',
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='apartment_type',
            field=models.CharField(choices=[('apartament', 'Apartament'), ('garsoniera', 'Garsoniera'), ('penthouse', 'Penthouse')], default='apartament', max_length=11, verbose_name='tip locuinţă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='balconies_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. balcoane'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='bathrooms_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. băi'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='building_type',
            field=models.CharField(choices=[('bloc-de-apartamente', 'bloc de apartamente'), ('casa-vila', 'casă/vilă')], default='bloc-de-apartamente', max_length=20, verbose_name='tip imobil'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='building_year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='An finalizare construcţii'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='buyer_commission',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='comision cumpărător'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='closed_balconies_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='din care închise'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='comfort',
            field=models.CharField(blank=True, choices=[('1', 'I'), ('2', 'Ii'), ('3', 'Iii'), ('lux', 'Lux')], default=None, max_length=3, verbose_name='confort'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='constructed_surface',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='suprafaţa construită'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='garages_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. garaje'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='parter'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_basement',
            field=models.BooleanField(default=False, verbose_name='are subsol'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_semi_basement',
            field=models.BooleanField(default=False, verbose_name='Are demisol'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='hide_address_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde adresa în imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='kitchens_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. bucătării'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='level',
            field=models.CharField(blank=True, choices=[('demisol', 'Demisol'), ('parter', 'Parter'), ('etaj-1', 'Etaj 1'), ('etaj-2', 'Etaj 2'), ('etaj-3', 'Etaj 3'), ('etaj-4', 'Etaj 4'), ('etaj-5', 'Etaj 5'), ('etaj-6', 'Etaj 6'), ('etaj-7', 'Etaj 7'), ('etaj-8', 'Etaj 8'), ('etaj-9', 'Etaj 9'), ('etaj-10', 'Etaj 10'), ('etaj-11', 'Etaj 11'), ('etaj-12', 'Etaj 12'), ('etaj-13', 'Etaj 13'), ('etaj-14', 'Etaj 14'), ('etaj-15', 'Etaj 15'), ('etaj-16', 'Etaj 16'), ('etaj-17', 'Etaj 17'), ('etaj-18', 'Etaj 18'), ('etaj-19', 'Etaj 19'), ('etaj-20', 'Etaj 20'), ('etaj-21', 'Etaj 21'), ('etaj-22', 'Etaj 22'), ('etaj-23', 'Etaj 23'), ('etaj-24', 'Etaj 24'), ('etaj-25', 'Etaj 25'), ('etaj-26', 'Etaj 26'), ('etaj-27', 'Etaj 27'), ('etaj-28', 'Etaj 28'), ('etaj-30', 'Etaj 30'), ('etaj-31', 'Etaj 31'), ('etaj-32', 'Etaj 32'), ('etaj-33', 'Etaj 33'), ('etaj-34', 'Etaj 34'), ('etaj-35', 'Etaj 35'), ('etaj-36', 'Etaj 36'), ('etaj-37', 'Etaj 37'), ('etaj-38', 'Etaj 38'), ('etaj-39', 'Etaj 39'), ('etaj-40', 'Etaj 40'), ('mansarda', 'Mansarda'), ('ultimele-2-etaje', 'Ultimele 2 etaje')], default=None, max_length=17, verbose_name='etaj'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='levels_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. niveluri'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='mansardă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='not_include_vat',
            field=models.BooleanField(default=False, verbose_name='nu include TVA'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='parking_lots_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. locuri parcare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='partitioning_type',
            field=models.CharField(blank=True, choices=[('decomandat', 'Decomandat'), ('semidecomandat', 'Semidecomandat'), ('nedecomandat', 'Nedecomandat'), ('circular', 'Circular'), ('vagon', 'Vagon')], default=None, max_length=15, verbose_name='tip compartimentare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='price_details',
            field=models.TextField(blank=True, default=None, verbose_name='alte detalii preţ'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='rooms_nr',
            field=models.PositiveIntegerField(default=None, verbose_name='nr. camere'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='total_util_surface',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='suprafaţa utilă totală'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='util_surface',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='suprafaţa utilă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='zero_commission',
            field=models.BooleanField(default=False, verbose_name='comision 0%'),
        ),
        migrations.AddField(
            model_name='commercialspacesale',
            name='hide_address_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde adresa în imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='housesale',
            name='hide_address_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde adresa în imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='industrialspacesale',
            name='hide_address_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde adresa în imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='landsale',
            name='hide_address_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde adresa în imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='hide_address_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde adresa în imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='specialpropertysale',
            name='hide_address_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde adresa în imobiliare.ro'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='is_residential_complex',
            field=models.BooleanField(default=False, verbose_name='ansamblu rezidenţial'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='residential_complex_link',
            field=models.URLField(blank=True, help_text='pagina detalii ansamblu rezidenţial promovat pe imobiliare.ro', null=True, verbose_name='link'),
        ),
    ]
