# Generated by Django 3.1 on 2020-09-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20200917_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsale',
            name='asphalted_street',
            field=models.BooleanField(default=False, verbose_name='asfaltate'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='building_period',
            field=models.CharField(blank=True, choices=[('_1941', 'Înainte de 1941'), ('1941_1977', 'Între 1941 şi 1977'), ('1977_1990', 'Între 1977 şî 1990'), ('1990_2000', 'Între 1990 şi 2000'), ('2000_2010', 'Între 2000 şi 2010'), ('2010_', 'După 2010')], default=None, max_length=10, verbose_name='perioada construire'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='concreted_street',
            field=models.BooleanField(default=False, verbose_name='betonate'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='display_expiry_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='dată expirare afişare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='disponibility',
            field=models.TextField(blank=True, default=None, verbose_name='disponibilitate proprietate'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='for_offices',
            field=models.BooleanField(default=False, verbose_name='birouri'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='for_vacation',
            field=models.BooleanField(default=False, verbose_name='de vacanţă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='aer condiţionat'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_air_heater',
            field=models.BooleanField(default=False, verbose_name='aeroterme'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_aluminium_rolls',
            field=models.BooleanField(default=False, verbose_name='aluminiu'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_aluminium_windows',
            field=models.BooleanField(default=False, verbose_name='aluminiu'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_building_boiler',
            field=models.BooleanField(default=False, verbose_name='centrală imobil'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_catv',
            field=models.BooleanField(default=False, verbose_name='CATV'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_current',
            field=models.BooleanField(default=False, verbose_name='curent'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_dial_up',
            field=models.BooleanField(default=False, verbose_name='dial-up'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_exclusivity',
            field=models.BooleanField(default=False, verbose_name='exclusivitate'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_fan',
            field=models.BooleanField(default=False, verbose_name='ventiloconvectoare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_fiber',
            field=models.BooleanField(default=False, verbose_name='fibră optică'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_fireplace_or_terracotta',
            field=models.BooleanField(default=False, verbose_name='sobă/teracotă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_flooring_heating',
            field=models.BooleanField(default=False, verbose_name='încălzire prin pardoseală'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_gas',
            field=models.BooleanField(default=False, verbose_name='gaz'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='termoficare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_horizontal_louver',
            field=models.BooleanField(default=False, verbose_name='orizontale'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_illuminated_street',
            field=models.BooleanField(default=False, verbose_name='iluminat stradal'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_international_phone',
            field=models.BooleanField(default=False, verbose_name='telefon internaţional'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_own_boiler',
            field=models.BooleanField(default=False, verbose_name='centrală proprie'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_phone',
            field=models.BooleanField(default=False, verbose_name='telefon'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_pvc_rolls',
            field=models.BooleanField(default=False, verbose_name='PVC'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_pvc_windows',
            field=models.BooleanField(default=False, verbose_name='PVC'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_radiator',
            field=models.BooleanField(default=False, verbose_name='calorifere'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_sewerage',
            field=models.BooleanField(default=False, verbose_name='canalizare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_vertical_louver',
            field=models.BooleanField(default=False, verbose_name='verticale'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_water',
            field=models.BooleanField(default=False, verbose_name='apă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_wired_net',
            field=models.BooleanField(default=False, verbose_name='cablu'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_wood_rolls',
            field=models.BooleanField(default=False, verbose_name='lemn'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_wood_windows',
            field=models.BooleanField(default=False, verbose_name='lemn'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='hotel_regime',
            field=models.BooleanField(default=False, verbose_name='Regim hotelier'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_comercial',
            field=models.BooleanField(default=False, verbose_name='comercial'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_good',
            field=models.BooleanField(default=False, verbose_name='bună'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_renovated',
            field=models.BooleanField(default=False, verbose_name='renovat'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_residential',
            field=models.BooleanField(default=False, verbose_name='rezidenţial'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_wireless',
            field=models.BooleanField(default=False, verbose_name='wireless'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='need_renovation',
            field=models.BooleanField(default=False, verbose_name='necesită renovare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='other_details',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='alte detalii'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='paved_street',
            field=models.BooleanField(default=False, verbose_name='pietruite'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='public_transport',
            field=models.BooleanField(default=False, verbose_name='mijloace de transport în comun'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='resistance_structure',
            field=models.CharField(blank=True, choices=[('beton', 'Beton'), ('caramida', 'cărămidă'), ('bca', 'Bca'), ('lemn', 'Lemn'), ('metale', 'Metale'), ('altele', 'Altele')], default=None, max_length=10, verbose_name='structura de rezistenţă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='soil_street',
            field=models.BooleanField(default=False, verbose_name='de pământ'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='undeveloped_street',
            field=models.BooleanField(default=False, verbose_name='neamenajate'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='vices',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='vicii'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='building_year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='an finalizare construcţie'),
        ),
    ]
