# Generated by Django 3.1 on 2020-09-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20200918_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentsale',
            old_name='mansard',
            new_name='has_mansard',
        ),
        migrations.RenameField(
            model_name='apartmentsale',
            old_name='is_wireless',
            new_name='has_wireless',
        ),
        migrations.RemoveField(
            model_name='apartmentsale',
            name='content',
        ),
        migrations.RemoveField(
            model_name='apartmentsale',
            name='ground_floor',
        ),
        migrations.RemoveField(
            model_name='apartmentsale',
            name='hotel_regime',
        ),
        migrations.RemoveField(
            model_name='apartmentsale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='commercialspacesale',
            name='content',
        ),
        migrations.RemoveField(
            model_name='housesale',
            name='content',
        ),
        migrations.RemoveField(
            model_name='industrialspacesale',
            name='content',
        ),
        migrations.RemoveField(
            model_name='landsale',
            name='content',
        ),
        migrations.RemoveField(
            model_name='officesale',
            name='content',
        ),
        migrations.RemoveField(
            model_name='specialpropertysale',
            name='content',
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='contract',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_administration',
            field=models.BooleanField(default=False, verbose_name='administrare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_alarm_system',
            field=models.BooleanField(default=False, verbose_name='sistem de alarmă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_auto_access_remote',
            field=models.BooleanField(default=False, verbose_name='telecomandă poartă access auto'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_basement_box',
            field=models.BooleanField(default=False, verbose_name='boxă la subsol'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_bed_sheets',
            field=models.BooleanField(default=False, verbose_name='lenjerie de pat'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_carpet_floor',
            field=models.BooleanField(default=False, verbose_name='mochetă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_cellular_interior_door',
            field=models.BooleanField(default=False, verbose_name='celulare'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_chalk_walls',
            field=models.BooleanField(default=False, verbose_name='var'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_city_tour',
            field=models.BooleanField(default=False, verbose_name='tur oraş'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_clay_walls',
            field=models.BooleanField(default=False, verbose_name='humă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_cleaning',
            field=models.BooleanField(default=False, verbose_name='curăţenie'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_coffee_maker',
            field=models.BooleanField(default=False, verbose_name='cafetieră'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_common_yard',
            field=models.BooleanField(default=False, verbose_name='curte comună'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_decking_floor',
            field=models.BooleanField(default=False, verbose_name='duşumea'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_dishwasher',
            field=models.BooleanField(default=False, verbose_name='maşină de spălat vase'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_dryer',
            field=models.BooleanField(default=False, verbose_name='uscătorie'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_dvd',
            field=models.BooleanField(default=False, verbose_name='DVD'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='lift'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_equipped_kitchen',
            field=models.BooleanField(default=False, verbose_name='utilată'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_exterior_pool',
            field=models.BooleanField(default=False, verbose_name='piscină exterioară'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_faience_walls',
            field=models.BooleanField(default=False, verbose_name='faianţă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_fireplace',
            field=models.BooleanField(default=False, verbose_name='şemineu'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_fridge',
            field=models.BooleanField(default=False, verbose_name='frigider'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_furnished_kitchen',
            field=models.BooleanField(default=False, verbose_name='mobilată'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_garage_remote',
            field=models.BooleanField(default=False, verbose_name='telecomandă poartă garaj'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name='grădină'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_gas_cooker',
            field=models.BooleanField(default=False, verbose_name='aragaz'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_gas_counter',
            field=models.BooleanField(default=False, verbose_name='contor gaz'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_glass_interior_door',
            field=models.BooleanField(default=False, verbose_name='sticlă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_ground_floor',
            field=models.BooleanField(default=True, editable=False, verbose_name='parter'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_hairdryer',
            field=models.BooleanField(default=False, verbose_name='uscător de păr'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_half_equipped_kitchen',
            field=models.BooleanField(default=False, verbose_name='parţial utilată'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_half_furnished_kitchen',
            field=models.BooleanField(default=False, verbose_name='parţial mobilată'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_heat_counter',
            field=models.BooleanField(default=False, verbose_name='contor căldură'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_hi_fi',
            field=models.BooleanField(default=False, verbose_name='Hi-Fi'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_hood',
            field=models.BooleanField(default=False, verbose_name='hotă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_housekeeping',
            field=models.BooleanField(default=False, verbose_name='menaj'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_indoor_heat_isolation',
            field=models.BooleanField(default=False, verbose_name='interior'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_intercom',
            field=models.BooleanField(default=False, verbose_name='interfon'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_interior_pool',
            field=models.BooleanField(default=False, verbose_name='piscină interioară'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_interior_stairway',
            field=models.BooleanField(default=False, verbose_name='scară interioară'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_iron',
            field=models.BooleanField(default=False, verbose_name='fier de călcat'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_jacuzzi',
            field=models.BooleanField(default=False, verbose_name='jacuzzi'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_kitchen_robot',
            field=models.BooleanField(default=False, verbose_name='robot bucătărie'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_linoleum_floor',
            field=models.BooleanField(default=False, verbose_name='linoleum'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_marble_floor',
            field=models.BooleanField(default=False, verbose_name='marmură'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_metal_entrance_door',
            field=models.BooleanField(default=False, verbose_name='metal'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_outdoor_heat_isolation',
            field=models.BooleanField(default=False, verbose_name='exterior'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_oven',
            field=models.BooleanField(default=False, verbose_name='cuptor cu microunde'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_pal_entrance_door',
            field=models.BooleanField(default=False, verbose_name='pal'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_panel_interior_door',
            field=models.BooleanField(default=False, verbose_name='panel'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_parquet_entrance_door',
            field=models.BooleanField(default=False, verbose_name='parchet'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_parquet_floor',
            field=models.BooleanField(default=False, verbose_name='parchet'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_pvc_entrance_door',
            field=models.BooleanField(default=False, verbose_name='PVC'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_pvc_interior_door',
            field=models.BooleanField(default=False, verbose_name='PVC'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_recreation_spaces',
            field=models.BooleanField(default=False, verbose_name='spaţii de agrement'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_roof',
            field=models.BooleanField(default=False, verbose_name='acoperiş'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_sandwich_maker',
            field=models.BooleanField(default=False, verbose_name='sandwich-maker'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_sauna',
            field=models.BooleanField(default=False, verbose_name='saună'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_security',
            field=models.BooleanField(default=False, verbose_name='pază'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_service_wc',
            field=models.BooleanField(default=False, verbose_name='WC serviciu'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_smoke_sensor',
            field=models.BooleanField(default=False, verbose_name='senzor de fum'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_spa',
            field=models.BooleanField(default=False, verbose_name='SPA'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_station_transfer',
            field=models.BooleanField(default=False, verbose_name='transfer aeroport/gară'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_storage_closet',
            field=models.BooleanField(default=False, verbose_name='debara'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_terrace',
            field=models.BooleanField(default=False, verbose_name='terasă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_tiles_floor',
            field=models.BooleanField(default=False, verbose_name='gresie'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_toaster',
            field=models.BooleanField(default=False, verbose_name='toaster'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_towels',
            field=models.BooleanField(default=False, verbose_name='prosoape'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_tv',
            field=models.BooleanField(default=False, verbose_name='tv'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_vacuum_cleaner',
            field=models.BooleanField(default=False, verbose_name='aspirator'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_video_intercom',
            field=models.BooleanField(default=False, verbose_name='video interfon'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_video_security',
            field=models.BooleanField(default=False, verbose_name='supraveghere video'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_vinarom_walls',
            field=models.BooleanField(default=False, verbose_name='vinarom'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_wainscot_walls',
            field=models.BooleanField(default=False, verbose_name='lambriu'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_wallpaper_walls',
            field=models.BooleanField(default=False, verbose_name='tapet'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_wash_machine',
            field=models.BooleanField(default=False, verbose_name='maşină de spălat haine'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_washable_paint_walls',
            field=models.BooleanField(default=False, verbose_name='vopsea lavabilă'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_water_counter',
            field=models.BooleanField(default=False, verbose_name='apometre'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_wood_entrance_door',
            field=models.BooleanField(default=False, verbose_name='lemn'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_wood_interior_door',
            field=models.BooleanField(default=False, verbose_name='lemn'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='has_yard',
            field=models.BooleanField(default=False, verbose_name='curte'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_full_furnished',
            field=models.BooleanField(default=False, verbose_name='complet'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_half_furnished',
            field=models.BooleanField(default=False, verbose_name='parţial'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_lux_furnished',
            field=models.BooleanField(default=False, verbose_name='lux'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='is_not_furnished',
            field=models.BooleanField(default=False, verbose_name='nemobilat'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='total_price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ total'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='total_price_currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('ron', 'RON'), ('usd', 'USD')], default='eur', max_length=4, verbose_name=''),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='util_price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ / mp util'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='util_price_currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('ron', 'RON'), ('usd', 'USD')], default='eur', max_length=4, verbose_name=''),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='validity_from',
            field=models.DateTimeField(blank=True, default=None, verbose_name='valabilitate de la'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='validity_up_to',
            field=models.DateTimeField(blank=True, default=None, verbose_name='până la'),
        ),
        migrations.AddField(
            model_name='commercialspacesale',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='commercialspacesale',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='commercialspacesale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='commercialspacesale',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='commercialspacesale',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='housesale',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='housesale',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='housesale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='housesale',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='housesale',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='industrialspacesale',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='industrialspacesale',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='industrialspacesale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='industrialspacesale',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='industrialspacesale',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='landsale',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='landsale',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='landsale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='landsale',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='landsale',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='specialpropertysale',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='specialpropertysale',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='specialpropertysale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='specialpropertysale',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='specialpropertysale',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='constructed_surface',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='suprafaţa construită (mp)'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='total_util_surface',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='suprafaţa utilă totală (mp)'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='util_surface',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='suprafaţa utilă (mp)'),
        ),
    ]
