# Generated by Django 3.1 on 2020-09-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20200920_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsale',
            name='has_ground_floor',
            field=models.BooleanField(default=True, verbose_name='parter'),
        ),
    ]
