# Generated by Django 3.1 on 2020-09-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20200920_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsale',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='preţ total'),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='util_price',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='preţ / mp util'),
        ),
    ]
