# Generated by Django 3.1 on 2020-09-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_remove_housesale_has_storage_closet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentsale',
            name='is_residential_complex',
        ),
        migrations.RemoveField(
            model_name='apartmentsale',
            name='residential_complex_link',
        ),
    ]
