# Generated by Django 3.1 on 2020-09-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_auto_20200921_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landsale',
            name='urban_coefficients_source',
            field=models.CharField(blank=True, choices=[('P.U.G', 'P.U.G'), ('Certificat de urbanism', 'Certificat de urbanism'), ('P.U.Z', 'P.U.Z'), ('P.U.D', 'P.U.D')], default=None, max_length=25, verbose_name='sursă informaţii coef. urbanistici'),
        ),
    ]
