# Generated by Django 3.1 on 2020-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_auto_20200921_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesale',
            name='building_stage',
            field=models.CharField(blank=True, choices=[('Există', 'Există'), ('În construcţie', 'În construcţie'), ('Proiect', 'Proiect')], default=None, max_length=15, verbose_name='stadiu construcţie'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='building_state',
            field=models.CharField(blank=True, choices=[('Modernizat', 'Modernizat'), ('Nemodernizat', 'Nemodernizat')], default=None, max_length=15, verbose_name='stare imobil'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='building_type',
            field=models.CharField(choices=[('Clădire de birouri', 'Clădire de birouri'), ('Casă/vilă', 'Casă/vilă'), ('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire mixtă', 'Clădire mixtă')], default=None, max_length=20, verbose_name='tip imobil'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='building_year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='an finalizare construcţie'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='buyer_commission',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='comision cumpărător'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='contract',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='officesale',
            name='has_entresol',
            field=models.BooleanField(default=True, verbose_name='mezanin'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='has_exclusivity',
            field=models.BooleanField(default=False, verbose_name='exclusivitate'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='has_ground_floor',
            field=models.BooleanField(default=True, verbose_name='parter'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='has_mansard',
            field=models.BooleanField(default=True, verbose_name='mansardă'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='has_parking_possibility',
            field=models.BooleanField(default=False, verbose_name='posibilitate parcare'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='has_semi_basement',
            field=models.BooleanField(default=False, verbose_name='demisol'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='has_terrace',
            field=models.BooleanField(default=True, verbose_name='terasă'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='hide_price',
            field=models.BooleanField(default=False, verbose_name='nu doresc să fie afişat vizitatorilor site-ului'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='levels_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. niveluri'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='not_include_vat',
            field=models.BooleanField(default=False, verbose_name='nu include TVA'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='occupation_degree',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='grad ocupare clădire (%)'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='office_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('C', 'C'), ('C+', 'C+')], default=None, max_length=2, verbose_name='clasă birouri'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='parking_spaces_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. locuri parcare'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='price',
            field=models.PositiveIntegerField(default=None, verbose_name='preţ cerut'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='price_currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('ron', 'RON'), ('usd', 'USD')], default='eur', max_length=4, verbose_name=''),
        ),
        migrations.AddField(
            model_name='officesale',
            name='price_details',
            field=models.TextField(blank=True, default=None, verbose_name='alte detalii preţ'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='property_description',
            field=models.TextField(blank=True, default=None, max_length=100, verbose_name='descriere proprietate'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='property_name',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='nume proprietate'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='purpose_recommendation',
            field=models.CharField(blank=True, choices=[('pentru investiţie', 'pentru investiţie'), ('pentru utilizare proprie', 'pentru utilizare proprie'), ('există şi produce venituri', 'există şi produce venituri')], default=None, max_length=30, verbose_name='recomandare utilizare proprietate'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='terrain_surface',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='total_surface',
            field=models.PositiveIntegerField(default=None, verbose_name='suprafaţă totală (mp)'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='underground_levels_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. niveluri subterane'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='validity_from',
            field=models.DateTimeField(blank=True, default=None, verbose_name='valabilitate de la'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='validity_up_to',
            field=models.DateTimeField(blank=True, default=None, verbose_name='până la'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='zero_commission',
            field=models.BooleanField(default=False, verbose_name='comision 0%'),
        ),
    ]
