# Generated by Django 3.1 on 2020-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_auto_20200923_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vecinătăţi'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vecinătăţi'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vecinătăţi'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vecinătăţi'),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vecinătăţi'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vecinătăţi'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vecinătăţi'),
        ),
    ]
