# Generated by Django 3.1 on 2020-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_auto_20200923_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesale',
            name='display_expiry_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='dată expirare afişare'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='disponibility',
            field=models.TextField(blank=True, default=None, verbose_name='disponibilitate proprietate'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='other_details',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='alte detalii'),
        ),
        migrations.AddField(
            model_name='officesale',
            name='vices',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='vicii'),
        ),
    ]
