# Generated by Django 3.1 on 2020-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_auto_20200926_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialspacesale',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AlterField(
            model_name='commercialspacesale',
            name='total_surface',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă totală (mp)'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='constructed_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='suprafaţa construită (amprentă la sol) (mp)'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='street_front',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, verbose_name='front stradal (m)'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='terrace_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă terase (mp)'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='unfolded_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='suprafaţă desfăşurată (mp)'),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='util_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='suprafaţa utilă (mp)'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AlterField(
            model_name='industrialspacesale',
            name='total_surface',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă totală (mp)'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AlterField(
            model_name='officesale',
            name='total_surface',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă totală (mp)'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AlterField(
            model_name='specialpropertysale',
            name='total_surface',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă totală (mp)'),
        ),
    ]
