# Generated by Django 3.1 on 2020-08-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grup', 'verbose_name_plural': 'Grupuri'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setare', 'verbose_name_plural': 'Setări'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilizator', 'verbose_name_plural': 'Utilizatori'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profile'},
        ),
    ]
