# Generated by Django 3.1 on 2020-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20200818_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pics', verbose_name='Imagine profil'),
        ),
    ]
