# Generated by Django 3.1 on 2020-08-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20200819_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descriere'),
        ),
    ]
