# Generated by Django 3.1 on 2020-08-27 15:13

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20200819_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=administration.models.get_default_profile_pic, upload_to='profile_pics', verbose_name='Imagine profil'),
        ),
    ]
