# Generated by Django 3.1 on 2020-09-04 08:59

import administration.models
from django.db import migrations, models
import django.utils.timezone
import main.utils
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20200827_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'grup', 'verbose_name_plural': 'grupuri'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'setare', 'verbose_name_plural': 'setări'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilizator', 'verbose_name_plural': 'utilizatori'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profiluri'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=main.utils.get_upload_path, verbose_name='imagine'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='valoare'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=administration.models.get_default_profile_pic, upload_to='profile_pics', verbose_name='imagine profil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, region=None, verbose_name='număr de telefon'),
        ),
    ]
