# Generated by Django 3.1 on 2020-09-04 17:12

import administration.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20200904_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='descriere'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=administration.models.get_default_profile_pic, null=True, upload_to='profile_pics', verbose_name='imagine profil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, verbose_name='număr de telefon'),
        ),
    ]
