# Generated by Django 3.1 on 2020-09-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20200904_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profil'},
        ),
    ]
