# Generated by Django 3.1 on 2020-09-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20200908_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profiluri utilizatori'},
        ),
    ]
