# Generated by Django 3.1 on 2020-09-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20200909_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
    ]
