# Generated by Django 3.1 on 2020-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_auto_20200914_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
    ]
