# Generated by Django 3.1 on 2020-10-17 08:30

import common.base_models
import common.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_auto_20200914_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare')),
                ('name', models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('image', common.base_models.SelectUploadFileModelField(blank=True, default=None, upload_to=common.utils.get_upload_path)),
                ('slug', models.SlugField(blank=True, default=None, max_length=300)),
                ('is_long', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('link', models.CharField(blank=True, default=None, max_length=200)),
                ('type', models.CharField(choices=[('InternalLink', 'Internal Link'), ('ExternalLink', 'External Link'), ('ScrollTo', 'Scroll To')], default='InternalLink', max_length=12)),
                ('is_published', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='administration.menuitem')),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['id', 'slug', 'is_published', 'order_index'], name='administrat_id_8c475c_idx'),
        ),
    ]
