version: '2.1'

services:
  backend:
    build: .
    container_name: proimo-backend
    volumes:
      - ./static/media:/app/media
    environment:
      - DB_NAME=proimo
      - DB_USER=root
      - DB_PASSWORD=parola01
      - DB_HOST=pdb
      - DB_PORT=5432
      - SECRET_KEY=m!fl!0rvwary88^u2&74jhmd!!a^uvpwxz+l_u=(vtffkgf4$g
      - DEBUG=False
      - GMAPS_API_KEY=AIzaSyB2vnqQSzHpO4Zg1JgbJPpfvUjsuPDznW0
    ports:
      - "8000:8000"
    networks:
      postgresdb:
      internal-net:
        aliases:
          - backend

networks:
  postgresdb:
    external:
      name: pdb
  internal-net:
      name: internal-net