version: '2.1'

services:
  web:
    build: .
    container_name: proimo-backend
    volumes:
      - ./static:/app/static
    environment:
      - DB_HOST=mdb
    env_file:
      - .env
    ports:
      - "8008:8008"
    networks:
      mariadb-net:
      internal-net:
        aliases:
          - backend

networks:
  mariadb-net:
    external:
      name: db-net
  internal-net:
      name: internal-net