version: '2.1'

services:
  backend:
    build: .
    container_name: proimo-backend
    volumes:
      - ./static:/app/static
    environment:
      - DB_HOST=pdb
    env_file:
      - .env
    ports:
      - "8008:8008"
    networks:
      postgresdb:
      internal-net:
        aliases:
          - backend

networks:
  postgresdb:
    external:
      name: pdb
  internal-net:
      name: internal-net