# Generated by Django 3.1 on 2020-08-12 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('address', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=15)),
                ('surface', models.IntegerField()),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
