# Generated by Django 3.1 on 2020-08-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
