# Generated by Django 3.1 on 2020-08-12 20:56

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200812_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('address', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=15)),
                ('surface', models.IntegerField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Announce',
        ),
    ]
