# Generated by Django 3.1 on 2020-08-14 05:11

import ckeditor_uploader.fields
from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_Images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='surface',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(null=True, upload_to=main.utils.get_file_name),
        ),
    ]
