# Generated by Django 3.1 on 2020-08-14 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_add_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 5, 24, 17, 36193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 5, 24, 17, 36214, tzinfo=utc)),
        ),
    ]
