# Generated by Django 3.1 on 2020-08-14 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_change_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
