# Generated by Django 3.1 on 2020-08-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_fix_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
