# Generated by Django 3.1 on 2020-08-14 14:10

from django.db import migrations, models
import django.utils.timezone
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=main.utils.get_file_name)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
