# Generated by Django 3.1 on 2020-08-14 14:19

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_update_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.get_file_name),
        ),
    ]
