# Generated by Django 3.1 on 2020-09-08 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare')),
            ],
            options={
                'verbose_name': 'judeţ',
                'verbose_name_plural': 'judeţe',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='common.county')),
            ],
            options={
                'verbose_name': 'localitate',
                'verbose_name_plural': 'localităţi',
            },
        ),
    ]
