# Generated by Django 3.1 on 2020-09-13 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200914_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
    ]
