# Generated by Django 3.1 on 2020-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200914_0005'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='county',
            name='common_coun_id_533e2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='county',
            name='common_coun_name_15a987_idx',
        ),
        migrations.RemoveIndex(
            model_name='locality',
            name='common_loca_id_b3e1cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='locality',
            name='common_loca_county__f5ea96_idx',
        ),
        migrations.RemoveIndex(
            model_name='locality',
            name='common_loca_name_5afdcd_idx',
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
    ]
