# Generated by Django 3.1 on 2020-08-18 15:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Conţinut'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(max_length=15, null=True, verbose_name='Preţ'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicat?'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='region',
            field=models.CharField(max_length=200, null=True, verbose_name='Regiunea'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='surface',
            field=models.IntegerField(default=0, null=True, verbose_name='Suprafaţă'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima modificare'),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(null=True, upload_to=main.utils.get_file_name, verbose_name='Imagine'),
        ),
    ]
