# Generated by Django 3.1 on 2020-08-19 20:00

import ckeditor_uploader.fields
from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20200818_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='Conţinut'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='surface',
            field=models.IntegerField(default=0, verbose_name='Suprafaţă'),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=main.utils.get_file_name, verbose_name='Imagine'),
        ),
    ]
