# Generated by Django 3.1 on 2020-08-27 15:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20200819_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='Nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima modificare')),
                ('slug', models.CharField(default=None, max_length=500)),
                ('is_for_sale', models.BooleanField(choices=[(True, 'Voi vinde'), (False, 'Voi închiria')], default=False, verbose_name='')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Adresa')),
                ('region', models.CharField(max_length=200, null=True, verbose_name='Regiunea')),
                ('price', models.CharField(max_length=15, null=True, verbose_name='Preţ')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat?')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='Conţinut')),
            ],
            options={
                'verbose_name': 'Apartament',
                'verbose_name_plural': 'Apartamente',
            },
        ),
        migrations.CreateModel(
            name='CommercialSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='Nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima modificare')),
                ('slug', models.CharField(default=None, max_length=500)),
                ('is_for_sale', models.BooleanField(choices=[(True, 'Voi vinde'), (False, 'Voi închiria')], default=False, verbose_name='')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Adresa')),
                ('region', models.CharField(max_length=200, null=True, verbose_name='Regiunea')),
                ('price', models.CharField(max_length=15, null=True, verbose_name='Preţ')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat?')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='Conţinut')),
            ],
            options={
                'verbose_name': 'Spaţiu comercial',
                'verbose_name_plural': 'Spaţii comerciale',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='Nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima modificare')),
                ('slug', models.CharField(default=None, max_length=500)),
                ('is_for_sale', models.BooleanField(choices=[(True, 'Voi vinde'), (False, 'Voi închiria')], default=False, verbose_name='')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Adresa')),
                ('region', models.CharField(max_length=200, null=True, verbose_name='Regiunea')),
                ('price', models.CharField(max_length=15, null=True, verbose_name='Preţ')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat?')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='Conţinut')),
            ],
            options={
                'verbose_name': 'Casă',
                'verbose_name_plural': 'Case',
            },
        ),
        migrations.CreateModel(
            name='IndustrialSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='Nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima modificare')),
                ('slug', models.CharField(default=None, max_length=500)),
                ('is_for_sale', models.BooleanField(choices=[(True, 'Voi vinde'), (False, 'Voi închiria')], default=False, verbose_name='')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Adresa')),
                ('region', models.CharField(max_length=200, null=True, verbose_name='Regiunea')),
                ('price', models.CharField(max_length=15, null=True, verbose_name='Preţ')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat?')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='Conţinut')),
            ],
            options={
                'verbose_name': 'Spaţiu industrial',
                'verbose_name_plural': 'Spaţii industriale',
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='Nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima modificare')),
                ('slug', models.CharField(default=None, max_length=500)),
                ('is_for_sale', models.BooleanField(choices=[(True, 'Voi vinde'), (False, 'Voi închiria')], default=False, verbose_name='')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Adresa')),
                ('region', models.CharField(max_length=200, null=True, verbose_name='Regiunea')),
                ('price', models.CharField(max_length=15, null=True, verbose_name='Preţ')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat?')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='Conţinut')),
            ],
            options={
                'verbose_name': 'Teren',
                'verbose_name_plural': 'Terenuri',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='Nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima modificare')),
                ('slug', models.CharField(default=None, max_length=500)),
                ('is_for_sale', models.BooleanField(choices=[(True, 'Voi vinde'), (False, 'Voi închiria')], default=False, verbose_name='')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Adresa')),
                ('region', models.CharField(max_length=200, null=True, verbose_name='Regiunea')),
                ('price', models.CharField(max_length=15, null=True, verbose_name='Preţ')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat?')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='Conţinut')),
            ],
            options={
                'verbose_name': 'Birou',
                'verbose_name_plural': 'Birouri',
            },
        ),
        migrations.CreateModel(
            name='SpecialProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='Nume')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima modificare')),
                ('slug', models.CharField(default=None, max_length=500)),
                ('is_for_sale', models.BooleanField(choices=[(True, 'Voi vinde'), (False, 'Voi închiria')], default=False, verbose_name='')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Adresa')),
                ('region', models.CharField(max_length=200, null=True, verbose_name='Regiunea')),
                ('price', models.CharField(max_length=15, null=True, verbose_name='Preţ')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat?')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='Conţinut')),
            ],
            options={
                'verbose_name': 'Proprietate specială',
                'verbose_name_plural': 'Proprietăţi speciale',
            },
        ),
        migrations.RemoveField(
            model_name='offerimage',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferImage',
        ),
    ]
