# Generated by Django 3.1 on 2020-08-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20200827_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='Preţ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiunea'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='Preţ'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiunea'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='Preţ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiunea'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='Preţ'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiunea'),
        ),
        migrations.AlterField(
            model_name='land',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='Preţ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiunea'),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='office',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='Preţ'),
        ),
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiunea'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='Preţ'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiunea'),
        ),
    ]
