# Generated by Django 3.1 on 2020-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20200827_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiune'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiune'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiune'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiune'),
        ),
        migrations.AlterField(
            model_name='land',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='land',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiune'),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiune'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Regiune'),
        ),
    ]
