# Generated by Django 3.1 on 2020-09-03 10:47

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20200827_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commercialspace',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrialspace',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialproperty',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_for_sale',
            field=models.CharField(choices=[('selling', 'Voi vinde'), ('rent', 'Voi închiria')], default='rent', max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='slug',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='is_for_sale',
            field=models.CharField(choices=[('selling', 'Voi vinde'), ('rent', 'Voi închiria')], default='rent', max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='slug',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_for_sale',
            field=models.CharField(choices=[('selling', 'Voi vinde'), ('rent', 'Voi închiria')], default='rent', max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='is_for_sale',
            field=models.CharField(choices=[('selling', 'Voi vinde'), ('rent', 'Voi închiria')], default='rent', max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='slug',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='land',
            name='is_for_sale',
            field=models.CharField(choices=[('selling', 'Voi vinde'), ('rent', 'Voi închiria')], default='rent', max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='land',
            name='slug',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='office',
            name='is_for_sale',
            field=models.CharField(choices=[('selling', 'Voi vinde'), ('rent', 'Voi închiria')], default='rent', max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='is_for_sale',
            field=models.CharField(choices=[('selling', 'Voi vinde'), ('rent', 'Voi închiria')], default='rent', max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='slug',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
