# Generated by Django 3.1 on 2020-09-03 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20200903_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='commercialspace',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='house',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='industrialspace',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='land',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='office',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='specialproperty',
            name='geolocation',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='land',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='Adresă'),
        ),
    ]
