# Generated by Django 3.1 on 2020-09-04 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_lead_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
    ]
