# Generated by Django 3.1 on 2020-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
    ]
