# Generated by Django 3.1 on 2020-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20200914_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
    ]
