# Generated by Django 3.1 on 2020-09-04 08:55

import ckeditor_uploader.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentrent',
            options={'verbose_name': 'apartament', 'verbose_name_plural': 'apartamente'},
        ),
        migrations.AlterModelOptions(
            name='commercialspacerent',
            options={'verbose_name': 'spaţiu comercial', 'verbose_name_plural': 'spaţii comerciale'},
        ),
        migrations.AlterModelOptions(
            name='houserent',
            options={'verbose_name': 'casă', 'verbose_name_plural': 'case'},
        ),
        migrations.AlterModelOptions(
            name='industrialspacerent',
            options={'verbose_name': 'spaţiu industrial', 'verbose_name_plural': 'spaţii industriale'},
        ),
        migrations.AlterModelOptions(
            name='landrent',
            options={'verbose_name': 'teren', 'verbose_name_plural': 'terenuri'},
        ),
        migrations.AlterModelOptions(
            name='officerent',
            options={'verbose_name': 'birou', 'verbose_name_plural': 'birouri'},
        ),
        migrations.AlterModelOptions(
            name='specialpropertyrent',
            options={'verbose_name': 'proprietate specială', 'verbose_name_plural': 'proprietăţi speciale'},
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(max_length=200, null=True, srid=4326, verbose_name='adresă'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='conţinut'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicat?'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='preţ'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='regiune'),
        ),
    ]
