# Generated by Django 3.1 on 2020-09-04 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_auto_20200904_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima modificare'),
        ),
    ]
