# Generated by Django 3.1 on 2020-09-04 15:24

from django.db import migrations, models
import django.db.models.deletion
import common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_auto_20200904_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPropertyRentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=common.utils.get_upload_path, verbose_name='imagine')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rents.specialpropertyrent')),
            ],
            options={
                'verbose_name': 'imagine',
                'verbose_name_plural': 'imagini',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeRentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=common.utils.get_upload_path, verbose_name='imagine')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rents.officerent')),
            ],
            options={
                'verbose_name': 'imagine',
                'verbose_name_plural': 'imagini',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandRentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=common.utils.get_upload_path, verbose_name='imagine')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rents.landrent')),
            ],
            options={
                'verbose_name': 'imagine',
                'verbose_name_plural': 'imagini',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrialSpaceRentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=common.utils.get_upload_path, verbose_name='imagine')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rents.industrialspacerent')),
            ],
            options={
                'verbose_name': 'imagine',
                'verbose_name_plural': 'imagini',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseRentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=common.utils.get_upload_path, verbose_name='imagine')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rents.houserent')),
            ],
            options={
                'verbose_name': 'imagine',
                'verbose_name_plural': 'imagini',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialSpaceRentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=common.utils.get_upload_path, verbose_name='imagine')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rents.commercialspacerent')),
            ],
            options={
                'verbose_name': 'imagine',
                'verbose_name_plural': 'imagini',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApartmentRentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=common.utils.get_upload_path, verbose_name='imagine')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rents.apartmentrent')),
            ],
            options={
                'verbose_name': 'imagine',
                'verbose_name_plural': 'imagini',
                'abstract': False,
            },
        ),
    ]
