# Generated by Django 3.1 on 2020-09-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20200904_1159'),
        ('rents', '0006_auto_20200904_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.userprofile'),
        ),
    ]
