# Generated by Django 3.1 on 2020-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0009_auto_20200908_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, verbose_name='alias'),
        ),
    ]
