# Generated by Django 3.1 on 2020-09-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0010_auto_20200909_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificare'),
        ),
    ]
