# Generated by Django 3.1 on 2020-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0012_auto_20200914_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industrialspacerent',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialpropertyrent',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='nume'),
        ),
    ]
