# Generated by Django 3.1 on 2020-09-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0015_auto_20200918_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentrent',
            name='rent_cost',
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='hotel_regime',
            field=models.BooleanField(default=False, verbose_name='regim hotelier'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='hotel_regime_currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('ron', 'RON'), ('usd', 'USD')], default='eur', max_length=4, verbose_name=''),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='hotel_regime_price',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='chirie / zi'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='not_include_vat',
            field=models.BooleanField(default=False, verbose_name='nu include TVA'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='price_details',
            field=models.TextField(blank=True, default=None, verbose_name='alte detalii preţ'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='rent',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='chirie / lună'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='commercialspacerent',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='commercialspacerent',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='commercialspacerent',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='commercialspacerent',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='houserent',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='houserent',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='houserent',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='houserent',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
        migrations.AddField(
            model_name='specialpropertyrent',
            name='hide_exact_location_on_imobiliare',
            field=models.BooleanField(default=False, verbose_name='ascunde localizarea exactă pe imobiliare.ro'),
        ),
        migrations.AddField(
            model_name='specialpropertyrent',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='vicinătăţi'),
        ),
        migrations.AddField(
            model_name='specialpropertyrent',
            name='postal_code',
            field=models.CharField(blank=True, default=True, max_length=50, verbose_name='cod poştal'),
        ),
        migrations.AddField(
            model_name='specialpropertyrent',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2, verbose_name='sectorul'),
        ),
    ]
