# Generated by Django 3.1 on 2020-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0016_auto_20200920_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentrent',
            old_name='rent',
            new_name='rent_cost',
        ),
        migrations.RemoveField(
            model_name='apartmentrent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='commercialspacerent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='houserent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='industrialspacerent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='landrent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='officerent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='specialpropertyrent',
            name='content',
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='commercialspacerent',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='houserent',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
        migrations.AddField(
            model_name='specialpropertyrent',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='descriere emoţională'),
        ),
    ]
