# Generated by Django 3.1 on 2020-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0020_auto_20200923_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrent',
            name='access_road_width',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='lăţime drum de acces (m)'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='asphalted_street',
            field=models.BooleanField(default=False, verbose_name='asfaltate'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='buyer_commission',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='comision cumpărător'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='can_be_demolished',
            field=models.BooleanField(default=False, verbose_name='construcţie demolabilă'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='can_be_splitted',
            field=models.BooleanField(default=False, verbose_name='parcelabil'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='classification',
            field=models.CharField(choices=[('Intravilan', 'Intravilan'), ('Extravilan', 'Extravilan')], default='Intravilan', max_length=12, verbose_name='clasificare'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='concreted_street',
            field=models.BooleanField(default=False, verbose_name='betonate'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='constructed_surface',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='suprafaţă construită (mp)'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='contract',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='landrent',
            name='cut',
            field=models.IntegerField(blank=True, default=None, help_text='Coeficientul de utilizare al terenului (suma suprafeţelor desfăşurate/suprafaţa totală * 100', verbose_name='C.U.T (%)'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='display_expiry_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='dată expirare afişare'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='disponibility',
            field=models.TextField(blank=True, default=None, verbose_name='disponibilitate proprietate'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='documents',
            field=models.TextField(blank=True, default=None, verbose_name='acte/avize'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='for_offices',
            field=models.BooleanField(default=False, verbose_name='birouri'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='for_vacation',
            field=models.BooleanField(default=False, verbose_name='de vacanţă'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_auto_access',
            field=models.BooleanField(default=False, verbose_name='acces auto'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_current',
            field=models.BooleanField(default=False, verbose_name='curent'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_exclusivity',
            field=models.BooleanField(default=False, verbose_name='exclusivitate'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_gas',
            field=models.BooleanField(default=False, verbose_name='gaz'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_illuminated_street',
            field=models.BooleanField(default=False, verbose_name='iluminat stradal'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_investment_opportunity',
            field=models.BooleanField(default=False, verbose_name='oportunitate de investiţie'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_irrigation_system',
            field=models.BooleanField(default=False, verbose_name='sistem irigaţie'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_sewerage',
            field=models.BooleanField(default=False, verbose_name='canalizare'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_three_phase_current',
            field=models.BooleanField(default=False, verbose_name='curent trifazic'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_utilities_nearby',
            field=models.BooleanField(default=False, verbose_name='utilităţi în zonă'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='has_water',
            field=models.BooleanField(default=False, verbose_name='apă'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='height_regime',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='regim înălţime (m)'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='is_comercial',
            field=models.BooleanField(default=False, verbose_name='comercial'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='is_near_road',
            field=models.BooleanField(default=False, verbose_name='la şosea'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='is_residential',
            field=models.BooleanField(default=False, verbose_name='rezidenţial'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='is_surrounded_terrain',
            field=models.BooleanField(default=False, verbose_name='teren  împrejmuit'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='land_type',
            field=models.CharField(choices=[('Construcţii', 'Constructii'), ('Agricol', 'Agricol'), ('Pădure', 'Padure'), ('Livadă', 'Livada'), ('Păşune', 'Pasune'), ('Fâneaţă', 'Faneata'), ('Heleşteu', 'Helesteu')], default='Construcţii', max_length=12, verbose_name='tip teren'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='not_include_vat',
            field=models.BooleanField(default=False, verbose_name='nu include TVA'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='other_details',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='alte detalii'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='paved_street',
            field=models.BooleanField(default=False, verbose_name='pietruite'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='plots_lot',
            field=models.BooleanField(default=False, verbose_name='lot parcele'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='plots_lot_name',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='nume lot parcele'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='pot',
            field=models.IntegerField(blank=True, default=None, help_text='Procentajul de ocupare al terenului (suprafaţa ocupată/suprafaţa totală * 100', verbose_name='P.O.T (%)'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='price_details',
            field=models.TextField(blank=True, default=None, verbose_name='alte detalii preţ'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='public_transport',
            field=models.BooleanField(default=False, verbose_name='mijloace de transport în comun'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='rent_cost',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='chirie / lună'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='rent_currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('ron', 'RON'), ('usd', 'USD')], default='eur', max_length=4, verbose_name=''),
        ),
        migrations.AddField(
            model_name='landrent',
            name='soil_street',
            field=models.BooleanField(default=False, verbose_name='de pământ'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='street_front',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='front stradal (m)'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='street_fronts_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. fronturi stradale'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='terrain_angle',
            field=models.IntegerField(blank=True, default=None, verbose_name='înclinaţie teren (%)'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='terrain_construction',
            field=models.BooleanField(default=False, verbose_name='construcţie pe teren'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='terrain_surface',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='suprafaţă teren'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='terrain_surface_type',
            field=models.CharField(choices=[('m', 'M'), ('ha', 'Ha')], default='m', max_length=3, verbose_name=''),
        ),
        migrations.AddField(
            model_name='landrent',
            name='undeveloped_street',
            field=models.BooleanField(default=False, verbose_name='neamenajate'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='urban_coefficients_source',
            field=models.CharField(blank=True, choices=[('P.U.G', 'P.U.G'), ('Certificat de urbanism', 'Certificat de urbanism'), ('P.U.Z', 'P.U.Z'), ('P.U.D', 'P.U.D')], default=None, max_length=25, verbose_name='sursă informaţii coef. urbanistici'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='validity_from',
            field=models.DateTimeField(blank=True, default=None, verbose_name='valabilitate de la'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='validity_up_to',
            field=models.DateTimeField(blank=True, default=None, verbose_name='până la'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='vices',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='vicii'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='zero_commission',
            field=models.BooleanField(default=False, verbose_name='comision 0%'),
        ),
    ]
