# Generated by Django 3.1 on 2020-09-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rents', '0021_auto_20200925_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerent',
            name='building_type',
            field=models.CharField(choices=[('Clădire de birouri', 'Clădire de birouri'), ('Casă/vilă', 'Casă/vilă'), ('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire mixtă', 'Clădire mixtă')], default=None, max_length=20, verbose_name='tip imobil'),
        ),
        migrations.CreateModel(
            name='SpaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, verbose_name='denumire spaţiu')),
                ('surface', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă disponibilă')),
                ('disponibility', models.CharField(blank=True, choices=[('Imediat', 'Imediat'), ('Închiriat', 'Închiriat'), ('Imediat', 'Imediat')], default=None, max_length=20, verbose_name='disponibilitate spaţiu')),
                ('disponibility_time', models.DateTimeField(blank=True, default=None, verbose_name='Dată disponibilitate/expirare')),
                ('rent_cost', models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='chirie netă/mp/lună')),
                ('rent_currency', models.CharField(choices=[('eur', 'EUR'), ('ron', 'RON'), ('usd', 'USD')], default='eur', max_length=4, verbose_name='')),
                ('hide_price', models.BooleanField(default=False, verbose_name='nu doresc să fie afişat vizitatorilor site-ului')),
                ('not_include_vat', models.BooleanField(default=False, verbose_name='se adaugă TVA')),
                ('has_maintenance', models.BooleanField(default=False, verbose_name='se adaugă costuri cu utilităţi/mentenanţă')),
                ('zero_commission', models.BooleanField(default=False, verbose_name='comision 0%')),
                ('rent_commission', models.CharField(blank=True, default=None, max_length=50, verbose_name='comision cerut la închiriere')),
                ('level', models.CharField(blank=True, choices=[('demisol', 'Demisol'), ('parter', 'Parter'), ('etaj-1', 'Etaj 1'), ('etaj-2', 'Etaj 2'), ('etaj-3', 'Etaj 3'), ('etaj-4', 'Etaj 4'), ('etaj-5', 'Etaj 5'), ('etaj-6', 'Etaj 6'), ('etaj-7', 'Etaj 7'), ('etaj-8', 'Etaj 8'), ('etaj-9', 'Etaj 9'), ('etaj-10', 'Etaj 10'), ('etaj-11', 'Etaj 11'), ('etaj-12', 'Etaj 12'), ('etaj-13', 'Etaj 13'), ('etaj-14', 'Etaj 14'), ('etaj-15', 'Etaj 15'), ('etaj-16', 'Etaj 16'), ('etaj-17', 'Etaj 17'), ('etaj-18', 'Etaj 18'), ('etaj-19', 'Etaj 19'), ('etaj-20', 'Etaj 20'), ('etaj-21', 'Etaj 21'), ('etaj-22', 'Etaj 22'), ('etaj-23', 'Etaj 23'), ('etaj-24', 'Etaj 24'), ('etaj-25', 'Etaj 25'), ('etaj-26', 'Etaj 26'), ('etaj-27', 'Etaj 27'), ('etaj-28', 'Etaj 28'), ('etaj-30', 'Etaj 30'), ('etaj-31', 'Etaj 31'), ('etaj-32', 'Etaj 32'), ('etaj-33', 'Etaj 33'), ('etaj-34', 'Etaj 34'), ('etaj-35', 'Etaj 35'), ('etaj-36', 'Etaj 36'), ('etaj-37', 'Etaj 37'), ('etaj-38', 'Etaj 38'), ('etaj-39', 'Etaj 39'), ('etaj-40', 'Etaj 40'), ('mansarda', 'Mansarda'), ('ultimele-2-etaje', 'Ultimele 2 etaje')], default=None, max_length=17, verbose_name='etaj')),
                ('divisible_space', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă minimă divizibilă')),
                ('description', models.TextField(blank=True, default=None, max_length=500, verbose_name='descriere')),
                ('has_parking', models.BooleanField(default=False, verbose_name='posibilitate parcare')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
