# Generated by Django 3.1 on 2020-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0022_auto_20200926_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerent',
            name='building_stage',
            field=models.CharField(blank=True, choices=[('Există', 'Există'), ('În construcţie', 'În construcţie'), ('Proiect', 'Proiect')], default=None, max_length=15, verbose_name='stadiu construcţie'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='building_state',
            field=models.CharField(blank=True, choices=[('Modernizat', 'Modernizat'), ('Nemodernizat', 'Nemodernizat')], default=None, max_length=15, verbose_name='stare imobil'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='building_year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='an finalizare construcţie'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='contract',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='officerent',
            name='has_entresol',
            field=models.BooleanField(default=False, verbose_name='mezanin'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='has_exclusivity',
            field=models.BooleanField(default=False, verbose_name='exclusivitate'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='has_ground_floor',
            field=models.BooleanField(default=True, verbose_name='parter'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='has_mansard',
            field=models.BooleanField(default=False, verbose_name='mansardă'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='has_parking_possibility',
            field=models.BooleanField(default=False, verbose_name='posibilitate parcare'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='has_semi_basement',
            field=models.BooleanField(default=False, verbose_name='demisol'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='has_terrace',
            field=models.BooleanField(default=False, verbose_name='terasă'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='levels_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. niveluri'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='office_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('C', 'C'), ('C+', 'C+')], default=None, max_length=2, verbose_name='clasă birouri'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='parking_spaces_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. locuri parcare'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='property_description',
            field=models.TextField(blank=True, default=None, max_length=100, verbose_name='descriere proprietate'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='property_name',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='nume proprietate'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='terrain_surface',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='total_surface',
            field=models.PositiveIntegerField(default=None, verbose_name='suprafaţă totală (mp)'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='underground_levels_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. niveluri subterane'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='validity_from',
            field=models.DateTimeField(blank=True, default=None, verbose_name='valabilitate de la'),
        ),
        migrations.AddField(
            model_name='officerent',
            name='validity_up_to',
            field=models.DateTimeField(blank=True, default=None, verbose_name='până la'),
        ),
    ]
