# Generated by Django 3.1 on 2020-09-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0023_auto_20200926_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacemodel',
            options={'verbose_name': 'spaţiu', 'verbose_name_plural': 'spaţii'},
        ),
        migrations.AlterField(
            model_name='spacemodel',
            name='disponibility_time',
            field=models.DateTimeField(blank=True, default=None, verbose_name='dată disponibilitate/expirare'),
        ),
    ]
