# Generated by Django 3.1 on 2020-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0025_auto_20200926_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='hotel_regime_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='chirie / zi'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='rent_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='chirie / lună'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AlterField(
            model_name='commercialspacerent',
            name='total_surface',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă totală (mp)'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='constructed_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='suprafaţa construită (amprentă la sol) (mp)'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='hotel_regime_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='chirie / zi'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='rent_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='chirie / lună'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='street_front',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, verbose_name='front stradal (m)'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='terrace_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă terase (mp)'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='unfolded_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='suprafaţă desfăşurată (mp)'),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='util_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='suprafaţa utilă (mp)'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='rent_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='chirie / lună'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AlterField(
            model_name='officerent',
            name='total_surface',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă totală (mp)'),
        ),
    ]
