# Generated by Django 3.1 on 2020-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0027_auto_20200926_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialspacerent',
            name='building_stage',
            field=models.CharField(blank=True, choices=[('Există', 'Există'), ('În construcţie', 'În construcţie'), ('Proiect', 'Proiect')], default=None, max_length=15, verbose_name='stadiu construcţie'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='building_type',
            field=models.CharField(choices=[('Producţie/servicii', 'Producţie/servicii'), ('Depozitare', 'Depozitare'), ('Logistică', 'Logistică')], default=None, max_length=50, verbose_name='tip proprietate'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='building_year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='an finalizare construcţie'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='contract',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_crane',
            field=models.BooleanField(default=False, verbose_name='macara'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_current',
            field=models.BooleanField(default=False, verbose_name='curent'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='lift'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_exclusivity',
            field=models.BooleanField(default=False, verbose_name='exclusivitate'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_gas',
            field=models.BooleanField(default=False, verbose_name='gaz'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_railway',
            field=models.BooleanField(default=False, verbose_name='cale ferată'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_ramp',
            field=models.BooleanField(default=False, verbose_name='rampă'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_roads',
            field=models.BooleanField(default=False, verbose_name='cale rutieră'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_slide_bridge',
            field=models.BooleanField(default=False, verbose_name='pod rulant'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_tir_access',
            field=models.BooleanField(default=False, verbose_name='acces tir'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='has_water',
            field=models.BooleanField(default=False, verbose_name='apă'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='levels_nr',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='nr. niveluri'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='occupation_degree',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='grad ocupare clădire (%)'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='platform_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă platformă (mp)'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='property_description',
            field=models.TextField(blank=True, default=None, max_length=100, verbose_name='descriere proprietate'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='property_name',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='nume proprietate'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='resistance_structure',
            field=models.CharField(blank=True, choices=[('Beton', 'Beton'), ('Zidărie', 'Zidărie'), ('Pereţi sandwich', 'Pereţi sandwich'), ('Metalică', 'Metalică'), ('Lemn', 'Lemn'), ('Prefabricate', 'Prefabricate')], default=None, max_length=40, verbose_name='structură rezistenţă'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='terrain_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă teren (mp)'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='total_surface',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă totală (mp)'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='validity_from',
            field=models.DateTimeField(blank=True, default=None, verbose_name='valabilitate de la'),
        ),
        migrations.AddField(
            model_name='industrialspacerent',
            name='validity_up_to',
            field=models.DateTimeField(blank=True, default=None, verbose_name='până la'),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='flooring_type',
            field=models.CharField(blank=True, choices=[('Mochetă dale', 'Mochetă dale'), ('Pardoseli pe bază de răşini poliuretan', 'Pardoseli pe bază de răşini poliuretan'), ('Pardoseli supraînălţate', 'Pardoseli supraînălţate'), ('Pardoseli pe bază de răşini epoxidice', 'Pardoseli pe bază de răşini epoxidice'), ('Covor PVC', 'Covor PVC'), ('Covoare PVC omogene', 'Covoare PVC omogene'), ('Covoare PVC eterogene', 'Covoare PVC eterogene'), ('Mochetă role', 'Mochetă role'), ('Parchet', 'Parchet'), ('Podea de lemn', 'Podea de lemn')], default=None, max_length=40, verbose_name='tip pardoseală'),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='climatizare'),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='has_heating_system',
            field=models.BooleanField(default=False, verbose_name='instalaţie încălzire'),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='has_lighting',
            field=models.BooleanField(default=False, verbose_name='iluminat'),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='has_windows',
            field=models.BooleanField(default=False, verbose_name='ferestre/luminatoare'),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='offices_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, verbose_name='suprafaţă birouri (mp)'),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='previous_purpose',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='destinaţie anterioară'),
        ),
    ]
